site_name: Interactive Tools

nav:
    - 'Getting Started':
        - Introduction : 'index.md'
        - Setup: 'setup.md'
    - Documentation:
        - Modes Cycling: 'modes-cycling.md'
        - Selection: 'selection.md'
        - Transform: 'transform.md'
        - Tools: 'tools.md'
        - Pie Menus: 'pie-menus.md'
        - Toggles: 'toggles.md'
        - Uv Tools: 'uv-tools.md'
        - Preferences: 'preferences.md'
    
theme: readthedocs